### ISSUE TITLE
User page not correctly working with Bitwig's mappings browser panel

### ISSUE THREAD

**Issue by yokaiichi** [dgmulf/Twister4Bitwig#3] opened 2019-02-26 14:13 UTC
So.... trying to use Bitwig's Mappings Browser Panel _seems_ to work correctly when you click any control in the UI and twist a knob in the User page. The assignment gets made and looks correct. But when you exit the Mappings Browser Panel, the knob doesn't actually _do_ anything at all. I've tried it on track volume controls, on automation knobs in standard Bitwig devices and in 3rd party VSTs, and nothing happens.

Oddly, the only VST Synth with an internal MIDI mapping feature that seems to work fine with your controller so far is VPS-Avenger. All knobs in the User page are recognized by Avenger and work perfectly with its internal MIDI mapping. Even momentary toggle buttons in the UI respond perfectly to a knob press (toggling ON while held, then toggling OFF when released).  But Pigments (by Arturia) does not recognize nor respond to the knobs in the User page at all. Like, it doesn't even "see" that you're twisting the knob, so it never makes the internal MIDI assignment to any of the CC numbers in the User page.  

System Deets:
Windows 10 Pro, i5 2500, 16 GB RAM, Audient iD14, Geforce 1080
Bitwig 2.5 Beta 7 (and also in Beta 8)

**Comment by dgmulf** [comment] 2019-03-07 06:15
Thanks for alerting me to these issues. I can't reproduce the problem you're having with the Mappings Browser panel. Do the mappings show up in the panel when you close and re-open it?

As for mapping inside VST plugins, I'm thinking it's an issue with VST3 specifically. For example, the VST2 versions of the FabFilter plugins work properly, but the VST3 versions don't. I'll have to bring this to Bitwig's attention.

**Comment by yokaiichi** [comment] 2019-03-14 11:53
Yes, the mappings are still there when leaving and returning to the Mappings Browser panel. The only avenue for investigation I can suggest is to look close at Pawnbroker's controller extension versus your new one and see if you can figure out where they're different in this regard. The mappings panel worked fine with page 2 knobs and Bitwig in their extension.

**Comment by dgmulf** [comment] 2020-07-23 03:53
If you have a project that demonstrates this issue, please attach it to this thread. Until then, I'm closing the issue, as I cannot reproduce it on any setup.

**Closed as completed by dgmulf** 2020-07-23 03:53 UTC
Labels: bug, can't reproduce
